
server:
  port: 9090

logging:
  path: /var/log/naceservice
  file: app
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nacedb?relaxAutoCommit=true&useSSL=false
    username: nace-user
    password: password
